/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.lge.warehouse.supervisor.ui;

import com.lge.warehouse.supervisor.WarehouseInventoryInfo;
import com.lge.warehouse.supervisor.WidgetInfo;
import com.lge.warehouse.util.CustomerStatus;
import com.lge.warehouse.util.InventoryName;
import com.lge.warehouse.util.NewWidgetInfo;
import com.lge.warehouse.util.Order;
import com.lge.warehouse.util.OrderStatusInfo;
import com.lge.warehouse.util.QuantifiedWidget;
import com.lge.warehouse.util.SystemEvent;
import com.lge.warehouse.util.WarehouseConnectionStatus;
import com.lge.warehouse.util.WarehouseInfo;
import com.lge.warehouse.util.WarehouseStatus;
import com.lge.warehouse.util.WidgetCatalog;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.SwingConstants;

/**
 *
 * @author kihyung2.lee
 */
public class SupervisorUi extends javax.swing.JFrame implements SupervisorUiUpdate{

    /**
     * Creates new form SupervisorUi
     */
    public SupervisorUi() {
        initComponents();
        initUiController();
        requestCatalog();
        //updateSystemStatusString();
        //drawRobotStatusString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelOrder = new javax.swing.JPanel();
        jScrollPaneOrder = new javax.swing.JScrollPane();
        jTextAreaOrderStatus = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxCompleteOrder = new javax.swing.JCheckBox();
        jCheckBoxPendingOrder = new javax.swing.JCheckBox();
        jCheckBoxBackorder = new javax.swing.JCheckBox();
        jCheckBoxInProgressOrder = new javax.swing.JCheckBox();
        jPanelInventory = new javax.swing.JPanel();
        jScrollPaneInventory = new javax.swing.JScrollPane();
        jTextAreaInventoryStatus = new javax.swing.JTextArea();
        jPanelInventoryManagement = new javax.swing.JPanel();
        jComboBoxInventory = new javax.swing.JComboBox();
        jComboBoxWidget = new javax.swing.JComboBox();
        jSpinnerWidgetQuantity = new javax.swing.JSpinner();
        jButtonInventoryAdd = new javax.swing.JButton();
        jButtonAddTest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelWidgetManagement = new javax.swing.JPanel();
        jTextFieldNewWidget = new javax.swing.JTextField();
        jTextFieldNewWidgetPrice = new javax.swing.JTextField();
        jButtonAddWidget = new javax.swing.JButton();
        jLabelWidgetManagement = new javax.swing.JLabel();
        jLabelWidgetNameToBeAdded = new javax.swing.JLabel();
        jLabelWidgetPriceToBeAdded = new javax.swing.JLabel();
        jPanelRobot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelLocation = new javax.swing.JLabel();
        jTextFieldRobotLocation = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelInventoryList = new javax.swing.JLabel();
        jLabelVisitedStation = new javax.swing.JLabel();
        jScrollPaneInventoryList = new javax.swing.JScrollPane();
        jTextAreaInventoryList = new javax.swing.JTextArea();
        jScrollPaneVisitedStation = new javax.swing.JScrollPane();
        jTextAreaVisitedStation = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabelNextStop = new javax.swing.JLabel();
        jLabelRobotStatus = new javax.swing.JLabel();
        jTextFieldNextStop = new javax.swing.JTextField();
        jTextFieldRobotStatus = new javax.swing.JTextField();
        jLabelWarehouseStatus = new javax.swing.JLabel();
        jTextFieldWarehouseStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextAreaOrderStatus.setEditable(false);
        jTextAreaOrderStatus.setColumns(20);
        jTextAreaOrderStatus.setRows(5);
        jScrollPaneOrder.setViewportView(jTextAreaOrderStatus);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCheckBoxCompleteOrder.setSelected(true);
        jCheckBoxCompleteOrder.setText("Complete");
        jCheckBoxCompleteOrder.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxCompleteOrderStateChanged(evt);
            }
        });

        jCheckBoxPendingOrder.setSelected(true);
        jCheckBoxPendingOrder.setText("Pending");
        jCheckBoxPendingOrder.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxPendingOrderStateChanged(evt);
            }
        });

        jCheckBoxBackorder.setSelected(true);
        jCheckBoxBackorder.setText("Backorder");
        jCheckBoxBackorder.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxBackorderStateChanged(evt);
            }
        });

        jCheckBoxInProgressOrder.setSelected(true);
        jCheckBoxInProgressOrder.setText("InProgress");
        jCheckBoxInProgressOrder.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxInProgressOrderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jCheckBoxCompleteOrder)
                .addGap(47, 47, 47)
                .addComponent(jCheckBoxPendingOrder)
                .addGap(54, 54, 54)
                .addComponent(jCheckBoxBackorder)
                .addGap(38, 38, 38)
                .addComponent(jCheckBoxInProgressOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxCompleteOrder)
                    .addComponent(jCheckBoxPendingOrder)
                    .addComponent(jCheckBoxBackorder)
                    .addComponent(jCheckBoxInProgressOrder))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelOrderLayout = new javax.swing.GroupLayout(jPanelOrder);
        jPanelOrder.setLayout(jPanelOrderLayout);
        jPanelOrderLayout.setHorizontalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneOrder)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOrderLayout.setVerticalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Order", jPanelOrder);

        jTextAreaInventoryStatus.setEditable(false);
        jTextAreaInventoryStatus.setColumns(20);
        jTextAreaInventoryStatus.setRows(5);
        jScrollPaneInventory.setViewportView(jTextAreaInventoryStatus);

        jPanelInventoryManagement.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jComboBoxInventory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inventory1", "Inventory2", "Inventory3" }));

        jComboBoxWidget.setModel(new javax.swing.DefaultComboBoxModel(){
            public int getSize() { return getCatalogSize(); }
            public Object getElementAt(int i) { return mWidgetCatalog.getWidgetInfoAt(i).getName();}
        });

        jSpinnerWidgetQuantity.setToolTipText("Adjust the number of widget to be added");
        jSpinnerWidgetQuantity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinnerWidgetQuantity.setOpaque(true);

        jButtonInventoryAdd.setText("Add");
        jButtonInventoryAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInventoryAddActionPerformed(evt);
            }
        });

        jButtonAddTest.setText("Add all(10ea)");
        jButtonAddTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTestActionPerformed(evt);
            }
        });

        jLabel1.setText("Inventory Management");

        javax.swing.GroupLayout jPanelInventoryManagementLayout = new javax.swing.GroupLayout(jPanelInventoryManagement);
        jPanelInventoryManagement.setLayout(jPanelInventoryManagementLayout);
        jPanelInventoryManagementLayout.setHorizontalGroup(
            jPanelInventoryManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventoryManagementLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelInventoryManagementLayout.createSequentialGroup()
                .addComponent(jComboBoxInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxWidget, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerWidgetQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAddTest, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInventoryAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelInventoryManagementLayout.setVerticalGroup(
            jPanelInventoryManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventoryManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInventoryManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInventoryManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxWidget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInventoryManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerWidgetQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonInventoryAdd)
                        .addComponent(jButtonAddTest))))
        );

        jPanelWidgetManagement.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonAddWidget.setText("Add a widget");
        jButtonAddWidget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddWidgetActionPerformed(evt);
            }
        });

        jLabelWidgetManagement.setText("Widget Management");

        jLabelWidgetNameToBeAdded.setText("Name");

        jLabelWidgetPriceToBeAdded.setText("Price");

        javax.swing.GroupLayout jPanelWidgetManagementLayout = new javax.swing.GroupLayout(jPanelWidgetManagement);
        jPanelWidgetManagement.setLayout(jPanelWidgetManagementLayout);
        jPanelWidgetManagementLayout.setHorizontalGroup(
            jPanelWidgetManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWidgetManagementLayout.createSequentialGroup()
                .addGroup(jPanelWidgetManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWidgetManagementLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelWidgetManagement))
                    .addGroup(jPanelWidgetManagementLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelWidgetNameToBeAdded)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNewWidget, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jLabelWidgetPriceToBeAdded)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNewWidgetPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(153, 153, 153)
                .addComponent(jButtonAddWidget))
        );
        jPanelWidgetManagementLayout.setVerticalGroup(
            jPanelWidgetManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWidgetManagementLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonAddWidget))
            .addGroup(jPanelWidgetManagementLayout.createSequentialGroup()
                .addComponent(jLabelWidgetManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelWidgetManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWidgetManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNewWidgetPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelWidgetPriceToBeAdded))
                    .addGroup(jPanelWidgetManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelWidgetNameToBeAdded)
                        .addComponent(jTextFieldNewWidget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanelInventoryLayout = new javax.swing.GroupLayout(jPanelInventory);
        jPanelInventory.setLayout(jPanelInventoryLayout);
        jPanelInventoryLayout.setHorizontalGroup(
            jPanelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelWidgetManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInventoryManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneInventory))
                .addContainerGap())
        );
        jPanelInventoryLayout.setVerticalGroup(
            jPanelInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventoryLayout.createSequentialGroup()
                .addComponent(jScrollPaneInventory, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInventoryManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelWidgetManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inventory", jPanelInventory);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelLocation.setText("Location");

        jTextFieldRobotLocation.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldRobotLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRobotLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabelLocation))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelInventoryList.setText("Inventory List");

        jLabelVisitedStation.setText("Visited Stations");

        jTextAreaInventoryList.setEditable(false);
        jTextAreaInventoryList.setColumns(20);
        jTextAreaInventoryList.setRows(5);
        jScrollPaneInventoryList.setViewportView(jTextAreaInventoryList);

        jTextAreaVisitedStation.setEditable(false);
        jTextAreaVisitedStation.setColumns(20);
        jTextAreaVisitedStation.setRows(5);
        jScrollPaneVisitedStation.setViewportView(jTextAreaVisitedStation);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInventoryList)
                    .addComponent(jScrollPaneInventoryList, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneVisitedStation, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisitedStation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInventoryList, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVisitedStation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneInventoryList, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(jScrollPaneVisitedStation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNextStop.setText("Next Stop");

        jLabelRobotStatus.setText("Robot Status");

        jTextFieldNextStop.setEditable(false);

        jTextFieldRobotStatus.setEditable(false);

        jLabelWarehouseStatus.setText("Warehouse Status");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNextStop)
                    .addComponent(jLabelRobotStatus)
                    .addComponent(jLabelWarehouseStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNextStop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRobotStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldWarehouseStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNextStop)
                    .addComponent(jTextFieldNextStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRobotStatus)
                    .addComponent(jTextFieldRobotStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWarehouseStatus)
                    .addComponent(jTextFieldWarehouseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelRobotLayout = new javax.swing.GroupLayout(jPanelRobot);
        jPanelRobot.setLayout(jPanelRobotLayout);
        jPanelRobotLayout.setHorizontalGroup(
            jPanelRobotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRobotLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelRobotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanelRobotLayout.setVerticalGroup(
            jPanelRobotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRobotLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Robot", jPanelRobot);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInventoryAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInventoryAddActionPerformed
        int inventoryID = jComboBoxInventory.getSelectedIndex();
        int quantity = ((Integer)jSpinnerWidgetQuantity.getValue()).intValue();
        WidgetInfo widgetInfo = mWidgetCatalog.getWidgetInfoAt(jComboBoxWidget.getSelectedIndex());

        WarehouseInventoryInfo warehouseInventoryInfo = new WarehouseInventoryInfo(1);
        
        if(widgetInfo == null) {
            return;
        }
        
        //System.out.println("quantity = " + quantity);
        //System.out.println(InventoryName.fromInteger(inventoryID));
        if(!mInventoryInfo.isWidgetAddable(InventoryName.fromInteger(inventoryID), widgetInfo))
            return;
        
        warehouseInventoryInfo.addNewWidgetToInventory(InventoryName.fromInteger(inventoryID), widgetInfo, quantity);
        mSupervisorUiController.sendWarehouseInventoryInfo(warehouseInventoryInfo);
        
        makeUiValueDefault();
    }//GEN-LAST:event_jButtonInventoryAddActionPerformed

    private void jButtonAddTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTestActionPerformed
      
        WarehouseInventoryInfo warehouseInventoryInfo = new WarehouseInventoryInfo(1);
       
        warehouseInventoryInfo.addNewWidgetToInventory(InventoryName.INVENTORY_1, mWidgetCatalog.getWidgetInfoAt(0), 10);
        warehouseInventoryInfo.addNewWidgetToInventory(InventoryName.INVENTORY_2, mWidgetCatalog.getWidgetInfoAt(1), 10);
        warehouseInventoryInfo.addNewWidgetToInventory(InventoryName.INVENTORY_2, mWidgetCatalog.getWidgetInfoAt(2), 10);
        warehouseInventoryInfo.addNewWidgetToInventory(InventoryName.INVENTORY_3, mWidgetCatalog.getWidgetInfoAt(3), 10);
        warehouseInventoryInfo.addNewWidgetToInventory(InventoryName.INVENTORY_3, mWidgetCatalog.getWidgetInfoAt(4), 10);
        if(mWidgetCatalog.getWidgetInfoCnt() > 5) {
            warehouseInventoryInfo.addNewWidgetToInventory(InventoryName.INVENTORY_1, mWidgetCatalog.getWidgetInfoAt(5), 10);
        }
        
 
        mSupervisorUiController.sendWarehouseInventoryInfo(warehouseInventoryInfo);
        makeUiValueDefault();
    }//GEN-LAST:event_jButtonAddTestActionPerformed

    private void jButtonAddWidgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddWidgetActionPerformed
        int price = 0;
        
        if(!mWidgetCatalog.isWdgetCatalogExpandable())
            return;
        
        try{
            price = Integer.parseInt(jTextFieldNewWidgetPrice.getText());
        } catch(NumberFormatException e) {
            return;
        }
        
        System.out.println("Widget Name = " + jTextFieldNewWidget.getText() + ", price = " + price);
        // Request to add new widget
        mSupervisorUiController.requestAddNewWidgetItem(jTextFieldNewWidget.getText(), price);
        
        
        // Update ui
        updateWidgetManagementUi();
    }//GEN-LAST:event_jButtonAddWidgetActionPerformed

    private void jCheckBoxCompleteOrderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxCompleteOrderStateChanged
        drawOrderStatusString();
    }//GEN-LAST:event_jCheckBoxCompleteOrderStateChanged

    private void jCheckBoxPendingOrderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxPendingOrderStateChanged
        drawOrderStatusString();
    }//GEN-LAST:event_jCheckBoxPendingOrderStateChanged

    private void jCheckBoxBackorderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxBackorderStateChanged
        drawOrderStatusString();
    }//GEN-LAST:event_jCheckBoxBackorderStateChanged

    private void jCheckBoxInProgressOrderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxInProgressOrderStateChanged
        drawOrderStatusString();
    }//GEN-LAST:event_jCheckBoxInProgressOrderStateChanged

    private boolean requestOrderStatus() {
        if(mSupervisorUiController == null)
            return false;
        
        System.out.println("request order status");
        mSupervisorUiController.requestOrderStatus();
        return true;
    }
    
    private boolean requestRobotStatus() {
        // To-Do
        return false;
    }
    
    private boolean requestInventoryStatus() {
        // To-Do
        return false;
    }
    
    private void updateInvenetoryManagementUi() {
//        boolean bEnable = false;
//        if(jTabbedPaneInfo.getSelectedIndex() == 1)
//            bEnable = true;
//        else
//            bEnable = false;
//        
//        jComboBoxInventory.setEnabled(bEnable);
//        jComboBoxWidget.setEnabled(bEnable);
//        jSpinnerWidgetQuantity.setEnabled(bEnable);
//        jButtonInventoryAdd.setEnabled(bEnable);
    }
    
    private void updateWidgetManagementUi() {
        boolean bEnable = mWidgetCatalog.isWdgetCatalogExpandable();
        
        jTextFieldNewWidget.setEnabled(bEnable);
        jTextFieldNewWidgetPrice.setEnabled(bEnable);
        jButtonAddWidget.setEnabled(bEnable);
    }
    
    private void updateInventoryComboBox() {
        System.out.println("jComboBoxWidget.getSelectedIndex() : " + jComboBoxWidget.getSelectedIndex());
        if(jComboBoxWidget.getSelectedIndex() == -1)
            jComboBoxWidget.setSelectedIndex(0);
    }
    
    private int getCatalogSize() {
        if(mWidgetCatalog == null)
            return 0;
        else
            return mWidgetCatalog.getWidgetInfoCnt();
    }
    
    private void requestCatalog() {
        if(mSupervisorUiController != null)
            mSupervisorUiController.requestWidgetCatalog();
             
    }
    
    private void initUiController() {
        mSupervisorUiController = new SupervisorUiController();
        mSupervisorUiController.setWidgetCatalogUpdateListener(this);
        new Thread(mSupervisorUiController).start();
    }
    
    private void makeUiValueDefault() {
        jSpinnerWidgetQuantity.setValue(new Integer(0));
    }
    
    private String getVisitedStationString(List<String> list) {
        StringBuffer sb = new StringBuffer();
        for(String string : list) {
            sb.append(string).append("\n");
        }
        
        return sb.toString();
    }
    
    private void drawOrderStatusString() {
        boolean bChkComplete = jCheckBoxCompleteOrder.isSelected();
        boolean bChkPending = jCheckBoxPendingOrder.isSelected();
        boolean bChkBackorder = jCheckBoxBackorder.isSelected();
        boolean bChkInProgress = jCheckBoxInProgressOrder.isSelected();
        StringBuffer sb = new StringBuffer();
        List<Order> orderList = new ArrayList<Order>();
        
        if(bChkComplete)
            orderList.addAll(mOrderStatus.getCompleteOrderList());
        if(bChkPending)
            orderList.addAll(mOrderStatus.getPendingOrderList());
        if(bChkBackorder)
            orderList.addAll(mOrderStatus.getBackOrderList());
        if(bChkInProgress)
            orderList.addAll(mOrderStatus.getInProgressOrderList());
        Collections.sort(orderList, new Order.OrderCompare());
        
        for(Order order : orderList) {
            sb.append(order.toString()).append("\n");
        }
         
        jTextAreaOrderStatus.setText(sb.toString());
    }
    
    private void updateSystemStatusString() {
        StringBuffer sb = new StringBuffer();
        String customerStatus = new String();
        String warehouseInfo = new String();
        
        if(mSystemStatus == null) {
            customerStatus = CustomerStatus.OFF.name();
            warehouseInfo = WarehouseInfo.OFF.name();
        } else {
            customerStatus = mSystemStatus.getCustomerStatus().name();
            warehouseInfo = mSystemStatus.getWarehouseInfo().name();
        }
        
        sb.append("Connection:").append(customerStatus);
        sb.append(" / Warehouse Manager:").append(warehouseInfo);
        //System.out.println(sb.toString());
        //jLabelSystemStatus.setText(sb.toString());
        //jLabelSystemStatus.setHorizontalAlignment(SwingConstants.RIGHT);
    }
    
    private void drawRobotStatusString() {
        jTextFieldRobotLocation.setText(mWarehouseStatus.getLocationOfBot());
        jTextAreaInventoryList.setText(QuantifiedWidget.getListString(mWarehouseStatus.getInventoryListOfBot()));
        jTextAreaVisitedStation.setText(getVisitedStationString(mWarehouseStatus.getVisitedStationListOfBot()));
        jTextFieldNextStop.setText(mWarehouseStatus.getNextStop());
        jTextFieldRobotStatus.setText(mWarehouseStatus.getRobotStatus().name());
        jTextFieldWarehouseStatus.setText(mWarehouseStatus.getWarehouseStatus().name());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupervisorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupervisorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupervisorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupervisorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupervisorUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTest;
    private javax.swing.JButton jButtonAddWidget;
    private javax.swing.JButton jButtonInventoryAdd;
    private javax.swing.JCheckBox jCheckBoxBackorder;
    private javax.swing.JCheckBox jCheckBoxCompleteOrder;
    private javax.swing.JCheckBox jCheckBoxInProgressOrder;
    private javax.swing.JCheckBox jCheckBoxPendingOrder;
    private javax.swing.JComboBox jComboBoxInventory;
    private javax.swing.JComboBox jComboBoxWidget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInventoryList;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelNextStop;
    private javax.swing.JLabel jLabelRobotStatus;
    private javax.swing.JLabel jLabelVisitedStation;
    private javax.swing.JLabel jLabelWarehouseStatus;
    private javax.swing.JLabel jLabelWidgetManagement;
    private javax.swing.JLabel jLabelWidgetNameToBeAdded;
    private javax.swing.JLabel jLabelWidgetPriceToBeAdded;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelInventory;
    private javax.swing.JPanel jPanelInventoryManagement;
    private javax.swing.JPanel jPanelOrder;
    private javax.swing.JPanel jPanelRobot;
    private javax.swing.JPanel jPanelWidgetManagement;
    private javax.swing.JScrollPane jScrollPaneInventory;
    private javax.swing.JScrollPane jScrollPaneInventoryList;
    private javax.swing.JScrollPane jScrollPaneOrder;
    private javax.swing.JScrollPane jScrollPaneVisitedStation;
    private javax.swing.JSpinner jSpinnerWidgetQuantity;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaInventoryList;
    private javax.swing.JTextArea jTextAreaInventoryStatus;
    private javax.swing.JTextArea jTextAreaOrderStatus;
    private javax.swing.JTextArea jTextAreaVisitedStation;
    private javax.swing.JTextField jTextFieldNewWidget;
    private javax.swing.JTextField jTextFieldNewWidgetPrice;
    private javax.swing.JTextField jTextFieldNextStop;
    private javax.swing.JTextField jTextFieldRobotLocation;
    private javax.swing.JTextField jTextFieldRobotStatus;
    private javax.swing.JTextField jTextFieldWarehouseStatus;
    // End of variables declaration//GEN-END:variables
    private SupervisorUiController mSupervisorUiController;
    private WidgetCatalog mWidgetCatalog;
    private OrderStatusInfo mOrderStatus;
    private WarehouseStatus mWarehouseStatus = new WarehouseStatus();
    private WarehouseInventoryInfo mInventoryInfo;
    private SystemEvent mSystemStatus;

    @Override
    public void updateCatalog(WidgetCatalog widgetCatalog) {
        //System.out.println("catalog success");
        mWidgetCatalog = widgetCatalog;
        jComboBoxWidget.updateUI();
        updateWidgetManagementUi();
        updateInventoryComboBox();

    }

    @Override
    public void updateOrderStatus(OrderStatusInfo orderStatus) {
        mOrderStatus = orderStatus;
        drawOrderStatusString();
    }

    @Override
    public void updateRobotStatus(WarehouseStatus warehouseStatus) {
        mWarehouseStatus = warehouseStatus;
        drawRobotStatusString();
    }

    @Override
    public void updateInvenetoryStatus(WarehouseInventoryInfo inventoryInfo) {
        //jTextAreaInventory.setText(inventoryStatus);
        mInventoryInfo = inventoryInfo;
        jTextAreaInventoryStatus.setText(mInventoryInfo.toString());
    }

    @Override
    public void updateSystemStatus(SystemEvent systemStatus) {
        mSystemStatus = systemStatus;
        System.out.println("Connection: " + systemStatus.getCustomerStatus());
        System.out.println("Warehouse Manager: " + systemStatus.getWarehouseInfo());
        updateSystemStatusString();
    }
    
    
}
